version: 2.1

jobs:
  run-lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}
      #       - v1-dependencies-
      - run:
          name: install dependencies
          command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x ./hadolint
      # - save_cache:
      #     paths:
      #       - ./.capstone
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: Run lint
          command: |
              . venv/bin/activate
              make lint 

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@1.0

workflows:
  deployment:
    jobs:
      - run-lint

  