version: 2.1

jobs:
  run-lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}
      #       - v1-dependencies-
      - run:
          name: install dependencies
          command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x ./hadolint
      # - save_cache:
      #     paths:
      #       - ./.capstone
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: Run lint
          command: |
              . venv/bin/activate
              make lint 

  build-docker-image:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: |
              docker system prune
              docker build -t capstone-project:8654tag .
              docker image ls
              echo "logging into Docker Hub"
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
              echo "Tag image"
              docker tag capstone-project:8654tag hazemzein/capstone-project.8654tag
              echo "Pushing images to Docker Hub"
              docker push hazemzein/capstone-project.8654tag
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@1.0

workflows:
  deployment:
    jobs:
      - run-lint
#      - build-docker-image


  